remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: IHC4BC, A dataset for predicting Ki67, Er, Pr, and Her2/neu statuses from H&E-stained breast cancer images
